env:
  global:
    - secure: XBXLqQ9JMxpi/FwmX0eSSv6vXvaBXs7sGtW36aHXTpIhcrUqRALff8dfUOZGeMUzfi2ay/Sy6UlC4DdybWe0NmcCg7eFNfKkIQjeheHLHwvevV2tiPCr0dzMWahg0vpKkeMEKjb9957j86P9dsxK2+0h5FiXubksghi1BSfwuP9kQVrtnGsYkNw+f38LpntKq5+uAWfQW9jyyrTdjIRgW4ru9DUW9FfHRhCxHp2Jpiut8iDlv4xwF3wU2J1O90HyALPZsgH1Y1dFD+OpVCTd1WETE4ei1Vx2XOcuTQGf7mrmmHlAfRjRZYHEdV0THiAcuRqTgU1Lsef6haTeMnAfvbEGskM0UmNK9xmWWmpZOvLXBv3Pn3wGbcDV0juOt5CZypvFSBao1xG5b+lIz1f4Tag6hqkUdBffIsf/OGVXIIHoUnyVosidJ2470lvojp1B27Ttqx3ybBImFGsnmIe3eiPVJen93tmM0lrVa6gDa1HOa3TDFZ1TjTBkk2Qs/KOk5uj514YqEObqgK+b84Ojv3Og0SAiUoXgzXjK2U+Ju/lXr+SfkHe4UCl9zxrWQEaxU5XcVP2jSPzRwvYJ4Cf1tfpnccr211EQoidHvxG54G0tURH64Q+cO15Hx3V0X5j0E6+aEQqRRqDxLIsiI7T75ZQWD1D8XfJazZyUnzBWahU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists_optional
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
