env:
  global:
    - secure: sKZ+EL1peLPCX7uwV3+pgdryd3Ae6rpnCD/aKDWTxY1ELWxaWdPb7STKo/JhEj3zLhukPf/uCjxm0O6ic7dMUPkSZlRRlhtHqKEJJ9WRZdiojva94fAvU7M+sH/Ry+r/KycuOCtZLF7jga//Rp0aZm1lD2R8KVMcSkOsedOFn9nrDEGdsxqqyfjtAWZF3KldVfbMe2Cg1OY4noadGjOxwe/LlNp3HO0RTXWWA/6SLhJjr1p0ZXL2WTzSj9JvKcuApIVlVQlngfOMbnbpbn+FtLByoXOqdAztIPPNil67hxQDvlYkimtFVNEMaFmif1nLvwa7Uxr3TRYWI7SmAqRRUaHpnw9J11hgPdvfALoakiFEUOsKK/kKySbuVr17SahlViKzXnjqq90o+u6o7eeA6+g5GlDaXsWUBSnLfhww9S9+Zy8WTwuciPQWepvzHU8bedLp7xR++IX3WJ4I9XIgj7fuF/xfKQd4uMXUDd5dlx2nBysCNws8PNXxKVqMTcG6zHMBKZ1v+FZtTqtXTbTWNxANaWbEww7kBJ+MFgCytUI43EtHIut/7Y69xyQ9hr1uD4X32ALlCMGa52qM9Zmen9BMz7M4wIh5f/6BiO0ZjcJnasG61inYyAh5jQxi1/cD9iIFeIwhZ+DivjtGTW4cn5yP4yfUrjBDNLkQhvWWBts=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists_optional
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
